import { test } from 'node:test';
import assert from 'node:assert/strict';
import Matter from 'matter-js';
import { Simulation } from '../src/simulation';
import { LocalTransport } from '../src/transport';
import { BUYER, GATE, HARDWARE, MILL, SECRET, SHOP, roomCounter, roomDoor, worldPoint, PRODUCTS } from '../src/model';
const {Body}=Matter;
function fixture(){const s=new Simulation(false);s.axe=1;s.money=140;s.player=s.create('player',1400,2020,19,19);s.truck=s.create('truck',1510,2150,69,124);return s;}
function advance(s:Simulation,n=60){for(let i=0;i<n;i++)s.step();}
test('new worlds start with only bare land and a worn axe',()=>{const s=new Simulation();assert.equal(s.axe,.6);assert.equal(s.money,0);assert.equal(s.truck,undefined);assert.equal([...s.entities.values()].filter(e=>!e.room&&['truck','mill','structure','plank'].includes(e.kind)).length,0);s.step();});
test('a cut tree falls over time and becomes three physical logs',()=>{const s=fixture();const tree=s.create('tree',1430,2010,20,20,{species:'pine',hp:2,maxHp:2});s.command({type:'chop',target:tree.id});advance(s,40);s.command({type:'chop',target:tree.id});advance(s,15);assert.equal(tree.hp,0);assert.ok(s.entities.has(tree.id));advance(s,90);assert.ok(!s.entities.has(tree.id));assert.equal([...s.entities.values()].filter(e=>e.kind==='log').length,3);});
test('distant chopping and duplicate network envelopes have no effect',()=>{const s=fixture();const tree=s.create('tree',2000,2000,20,20,{hp:5,maxHp:5});s.command({type:'chop',target:tree.id});assert.equal(tree.hp,5);const msg={actor:'local',tick:0,seq:1,command:{type:'lights'} as const};s.receive(msg);s.receive(msg);advance(s,1);assert.equal(s.lights,true);s.receive({...msg,seq:2,actor:'stranger'});advance(s,1);assert.equal(s.lights,true);});
test('sawmill consumes a log and emits physical planks; scale pays only delivered wood',()=>{const s=fixture();s.create('mill',MILL.x,MILL.y,200,64);const log=s.create('log',MILL.x-80,MILL.y+10,65,20,{species:'pine'});advance(s,220);assert.ok(!s.entities.has(log.id));const planks=[...s.entities.values()].filter(e=>e.kind==='plank');assert.equal(planks.length,2);const money=s.money;advance(s,100);assert.equal(s.money,money);Body.setPosition(planks[0].body,BUYER);advance(s,110);assert.ok(!s.entities.has(planks[0].id));assert.ok(s.money>money);});
test('building requires local physical boards and dismantling returns them',()=>{const s=fixture();s.command({type:'build',piece:'wall',x:1430,y:2020,angle:0});assert.equal([...s.entities.values()].filter(e=>e.kind==='structure').length,0);for(let i=0;i<2;i++)s.create('plank',1370+i*22,2050,65,14);s.command({type:'build',piece:'wall',x:1430,y:2020,angle:0});const structure=[...s.entities.values()].find(e=>e.kind==='structure')!;assert.ok(structure);assert.equal([...s.entities.values()].filter(e=>e.kind==='plank').length,0);s.command({type:'remove',target:structure.id});assert.equal([...s.entities.values()].filter(e=>e.kind==='plank').length,2);});
test('spring dragging has reach limits and releases cleanly',()=>{const s=fixture();const log=s.create('log',1450,2020,65,20);s.command({type:'grab',target:log.id});s.command({type:'aim',x:1490,y:2080});advance(s,40);assert.equal(s.held,log.id);assert.ok(log.body.position.y>2025);s.command({type:'release'});assert.equal(s.held,null);Body.setPosition(log.body,{x:1900,y:2500});s.command({type:'grab',target:log.id});assert.equal(s.held,null);});
test('cargo can enter the truck bed and rope attachments survive snapshots',()=>{const s=fixture();Body.setPosition(s.player.body,{x:1500,y:2160});const log=s.create('log',1510,2190,65,20,{species:'pine'});s.command({type:'rope'});assert.equal(log.tied,true);s.command({type:'interact'});assert.equal(s.driving,true);s.command({type:'move',x:0,y:-1});advance(s,100);assert.ok(s.truck.body.position.y<2100);assert.ok(Math.hypot(log.body.position.x-s.truck.body.position.x,log.body.position.y-s.truck.body.position.y)<110);const saved=s.capture();const restored=fixture();restored.restore(saved);assert.equal(restored.driving,true);assert.equal(restored.entities.get(log.id)?.tied,true);restored.command({type:'rope'});assert.equal(restored.entities.get(log.id)?.tied,false);});
test('an unmarked mechanism responds to a physically delivered object',()=>{const s=fixture();s.create('rock',3560,SECRET.y,70,160,{owner:'secret'});const relic=s.create('relic',3505,SECRET.y,26,26);advance(s,1);assert.equal(s.secretOpen,true);assert.ok(!s.entities.has(relic.id));});
test('snapshot preserves economy and world and rejects corruption before modifying it',()=>{const s=fixture();s.money=413;s.create('dynamite',1310,2100,26,15,{paid:true,product:'dynamite'});s.create('structure',1300,2050,64,64,{piece:'floor'});const snapshot=s.capture(),restored=fixture();restored.restore(JSON.parse(JSON.stringify(snapshot)));assert.deepEqual(JSON.parse(JSON.stringify(restored.capture())),JSON.parse(JSON.stringify(snapshot)));assert.throws(()=>restored.restore({...snapshot,version:4} as never));assert.equal(restored.money,413);});
test('local transport serializes commands and ticks without renderer dependencies',()=>{const s=fixture();const port=new LocalTransport(e=>s.receive(e),()=>s.tick);port.send({type:'move',x:1,y:0});advance(s,30);assert.ok(s.player.body.position.x>1450);});
