import { CHUNK, LANDMARKS, PASSAGES, REGIONS, WORLD, riverX, type Passage, type Point } from './data';
import { heightAt, regionAt, regionWeights, roadDistance } from './terrain';

function forestAt(p:Point,choice:number){const weights=regionWeights(p),total=weights.reduce((a,b)=>a+b,0);let at=choice*total;for(let i=0;i<weights.length;i++){at-=weights[i];if(at<=0)return REGIONS[i].forest;}return regionAt(p).forest;}
export function biomeAt(p:Point){if(p.x<4600&&p.y<3700)return p.y<1040&&p.x>2530?'snow':p.x>3590&&p.y<1830?'gold':p.y>2850?'marsh':'forest';const r=regionAt(p);return r.forest==='snow'?'snow':r.forest==='gold'?'gold':r.id==='varzea'?'marsh':'forest';}
export function inRiver(p:Point){return Math.abs(p.x-riverX(p.y))<75&&!PASSAGES.some(b=>b.kind==='bridge'&&Math.abs(b.x-riverX(b.y))<200&&Math.abs(p.y-b.y)<(b.id==='old-bridge'?120:80));}
export const passageOpen=(p:Passage,unlocks:ReadonlySet<string>)=>p.open||unlocks.has(p.id);
export function blockedPassage(p:Point,unlocks:ReadonlySet<string>){return PASSAGES.find(g=>!passageOpen(g,unlocks)&&Math.hypot(p.x-g.x,p.y-g.y)<g.radius);}
export function traversable(a:Point,b:Point,unlocks:ReadonlySet<string>,driving=false){const d=Math.hypot(a.x-b.x,a.y-b.y);if(d<.001)return true;const steps=Math.max(1,Math.ceil(d/8));let prev=a;for(let i=1;i<=steps;i++){const p={x:a.x+(b.x-a.x)*i/steps,y:a.y+(b.y-a.y)*i/steps};if(p.x<12||p.y<12||p.x>WORLD.w-12||p.y>WORLD.h-12||inRiver(p))return false;const gate=blockedPassage(p,unlocks);if(gate&&Math.hypot(p.x-gate.x,p.y-gate.y)<Math.hypot(prev.x-gate.x,prev.y-gate.y))return false;const grade=Math.abs(heightAt(p)-heightAt(prev))/Math.max(.1,Math.hypot(p.x-prev.x,p.y-prev.y));if(grade>(driving?.65:1.0))return false;prev=p;}return true;}
export function chunkKey(p:Point,size=CHUNK){return Math.floor(p.x/size)+','+Math.floor(p.y/size);}
export function hash(a:number,b:number,c=0){let h=Math.imul(a+7919,374761393)^Math.imul(b+4099,668265263)^Math.imul(c+11,1274126177);h=Math.imul(h^(h>>>13),1274126177);return((h^(h>>>16))>>>0)/4294967296;}
export function treeSeeds(cx:number,cy:number){const trees:{id:string;x:number;y:number;species:'pine'|'birch'|'snow'|'gold';size:number;seed:number}[]=[];for(let i=0;i<60;i++){const x=(cx+hash(cx,cy,i*3))*CHUNK,y=(cy+hash(cx,cy,i*3+1))*CHUNK,p={x,y},r=regionAt(p);if(i>=r.density||x<4600&&y<3700||x<80||y<80||x>WORLD.w-80||y>WORLD.h-80||inRiver(p)||roadDistance(p)<115||LANDMARKS.some(l=>Math.hypot(x-l.x,y-l.y)<180)||PASSAGES.some(l=>Math.hypot(x-l.x,y-l.y)<230))continue;if(Math.abs(heightAt({x:x+35,y})-heightAt({x:x-35,y}))>50||Math.abs(heightAt({x,y:y+35})-heightAt({x,y:y-35}))>50)continue;const size=.8+hash(cx,cy,i+180)*.65,forest=forestAt(p,hash(cx,cy,i+380));trees.push({id:`w:${cx}:${cy}:${i}`,x,y,species:forest==='pine'&&hash(cx,cy,i+250)>.85?'birch':forest,size,seed:Math.floor(hash(cx,cy,i+300)*1e7)});}return trees;}
