import { BUILD } from '../model';

export const icon=(name:string)=>`<svg viewBox="0 0 24 24" aria-hidden="true">${({axe:'<path d="m5 21 9-14M12 3l-3 6 7 4 5-8-6-3-3 1Z"/>',hand:'<path d="M8 12V5a2 2 0 0 1 4 0v7-9a2 2 0 0 1 4 0v9-7a2 2 0 0 1 4 0v10c0 5-3 7-7 7-3 0-5-2-6-4l-4-6a2 2 0 0 1 3-2l2 2Z"/>',build:'<path d="m3 10 9-7 9 7M5 9v12h14V9M9 21v-8h6v8"/>',dynamite:'<path d="m5 9 9-4 5 13-9 4-5-13ZM14 5c-2-6 7-2 5-5M5 12l10-4M8 19l10-4"/>',map:'<path d="m3 5 6-2 6 3 6-2v16l-6 2-6-3-6 2V5Zm6-2v16M15 6v16"/>',coin:'<circle cx="12" cy="12" r="9"/><path d="M15 8h-4a2 2 0 0 0 0 4h2a2 2 0 0 1 0 4H9M12 6v12"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1 1M18 18l1 1M19 5l-1 1M6 18l-1 1"/>',menu:'<path d="M5 7h14M5 12h14M5 17h14"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>'} as Record<string,string>)[name]??''}</svg>`;

export function mountUi(){
  document.querySelector('#ui')!.innerHTML=`
<section id="intro" aria-label="Woodventure — início"><div class="intro-coordinate">VALE DO CEDRO<br><span style="opacity:.55">OUTONO, 16:12</span></div><div class="intro-copy"><div class="overline">UM LUGAR PARA FICAR</div><h1 aria-label="Woodventure">Wood<span>venture.</span></h1><p>Um machado gasto.<br>Um pedaço de terra.<br>O resto está lá fora.</p><button class="begin" id="begin">Chegar ao vale ${icon('arrow')}</button><button class="secondary" id="new-intro" hidden>Novo começo · terreno vazio</button><br><button class="secondary" id="intro-guide">Antes de sair · controles</button></div><div class="intro-footer"><span>MADEIRA, CAMINHOS E SILÊNCIO.<br>Jogue no seu tempo.</span><span>PROTÓTIPO 0.4 · ALÉM DO VALE<br>Um mundo salvo neste navegador.</span></div></section>
<div id="hud" hidden><div class="hud-top"><div><div class="small" id="region-small">DISTRITO FLORESTAL</div><div class="place" id="region">Entre pinheiros</div><div class="wallet">${icon('coin')}<strong id="money">140</strong></div></div><div class="weather">${icon('sun')}<div><div class="clock" id="time">16:12</div><div class="small" id="weather">BRISA LEVE</div></div><button class="icon-button" id="pause" aria-label="Abrir menu">${icon('menu')}</button></div></div>
<div id="toast" role="status"></div><div id="context" hidden></div><div id="driving" hidden><span id="speed">0 KM/H</span> · <span id="fuel-label">TANQUE</span><div class="fuel-track"><span id="fuel"></span></div></div>
<section class="build-menu" id="build-menu" hidden><div class="eyebrow">NA SUA PROPRIEDADE</div>${Object.entries(BUILD).map(([id,p])=>`<button data-piece="${id}" class="${id==='floor'?'active':''}">${p.name}<span>${p.cost} ${p.cost===1?'tábua':'tábuas'}</span></button>`).join('')}<p>Use as tábuas deixadas no chão.<br>Clique para colocar · Q para girar<br>Botão direito para desmontar.</p></section>
<div class="hud-bottom"><nav class="tools" aria-label="Ferramentas">${[['axe','Machado'],['hand','Mãos'],['build','Construir'],['dynamite','Dinamite']].map(([id,name],i)=>`<button class="tool ${i===0?'active':''}" data-tool="${i}" aria-label="${name}" title="${name} · ${i+1}"><kbd>${i+1}</kbd>${icon(id)}<span class="toolname">${name}</span></button>`).join('')}</nav><div class="bottom-actions"><button id="camera-button" title="Girar a câmera · Shift+C gira ao contrário; V muda inclinação"><kbd>C</kbd>Vista</button><button id="map-button"><kbd>M</kbd>Mapa</button><button id="help-button" class="hide-small"><kbd>H</kbd>Controles</button><button id="photo-button" class="hide-small" title="Modo fotografia"><kbd>P</kbd>Olhar</button></div></div><div id="save-state"></div>
<div class="touch-controls"><div class="arrows"><button data-key="w" aria-label="Mover para cima">↑</button><button data-key="a" aria-label="Mover à esquerda">←</button><button data-key="s" aria-label="Mover para baixo">↓</button><button data-key="d" aria-label="Mover à direita">→</button></div><div class="actions"><button data-action="interact">E</button><button data-action="chop">Cortar</button><button data-action="rope">R</button></div></div></div>
<div id="death" hidden><div class="eyebrow">O PAVIO ERA CURTO.</div><h2>A explosão atingiu você.</h2><p>Voltando ao seu terreno…</p></div><div id="placement" hidden><strong id="placement-name"></strong><span>Clique para instalar · Q gira · Esc cancela</span></div><div id="photo-hint" hidden>P · VOLTAR</div>
<dialog id="pause-dialog"><button class="close" aria-label="Fechar">×</button><div class="eyebrow">WOODVENTURE</div><h2>Uma pausa.</h2><div class="menu-buttons"><button id="resume">Voltar ao vale</button><button id="save">Salvar mundo</button><button id="export">Baixar cópia do mundo</button><button id="import">Carregar cópia do mundo</button><button id="sound">Som ambiente · ligado</button><button id="fullscreen">Tela cheia</button><button id="guide-menu">Controles e pequenas notas</button><button id="new-world">Novo começo · guardar este mundo e recomeçar</button><button id="previous-world">Voltar ao mundo anterior</button></div><p>Seu progresso fica neste navegador. Uma cópia do mundo permite levá-lo com você.</p></dialog>
<dialog id="help-dialog"><button class="close" aria-label="Fechar">×</button><div class="eyebrow">NO SEU TEMPO</div><h2>O básico para sair.</h2>${[['W A S D / setas','Caminhar. No veículo, acelerar e esterçar.'],['Clique / Espaço','Golpear uma árvore ou cortar uma tora. Segure para continuar.'],['Botão direito','Segurar e arrastar um objeto próximo. Solte para largar.'],['2 + clique','Também pega e solta madeira. Q gira o objeto.'],['E','Entrar na loja ou no carro. No balcão, pagar os produtos próximos.'],['E na travessia','Reparar uma ponte com as tábuas entregues no local.'],['M no mapa','Arrastar explora, roda aproxima e clique anota um destino.'],['R','Amarrar ou soltar o que está na caçamba.'],['Espaço no carro','Frear. Veículos carregados respondem diferente.'],['3 / B','Construir. Q gira a peça. Tábuas precisam estar por perto.'],['X','Abrir caixa / equipar machado / posicionar refinadora.'],['4 + clique','Acender uma dinamite próxima. Afaste-se da explosão.'],['F · M · P','Lanterna e faróis · mapa · olhar sem interface.'],['C / Shift + C','Girar a câmera para os dois lados.'],['V / Home','Alternar inclinação / restaurar a vista.'],['Roda do mouse','Aproximar ou afastar a câmera.'],['Esc','Pausar e salvar.']].map(([k,v])=>`<div class="guide-row"><kbd>${k}</kbd><span>${v}</span></div>`).join('')}<p>Madeira em cima da balança é vendida. Leve produtos da prateleira ao balcão e aperte E para pagar. Carregue as caixas até o terreno e use X para instalar. Empurre toras pela mesa da refinadora marcada com faixas claras. O que você constrói usa madeira de verdade, deixada no chão.</p><p>Nas terras altas, procure a estrada de subida. Leve tábuas para reparar travessias e dinamite para abrir desmoronamentos. Abasteça a caminhonete antes de viagens longas. Não há pressa. Nem tudo está desenhado no mapa.</p></dialog>
<dialog id="map-dialog"><button class="close" aria-label="Fechar">×</button><header class="atlas-heading"><div><div class="eyebrow">DISTRITO FLORESTAL · CADERNO DE CAMPO</div><h2>Além do vale.</h2></div><span id="atlas-discovery"></span></header><div class="atlas-layout"><aside class="atlas-sidebar"><div class="eyebrow">SUA ANOTAÇÃO</div><h3 id="atlas-place"></h3><p id="atlas-detail"></p><button data-atlas="me">◎ Meu local</button><button data-atlas="fit">↗ Território inteiro</button><button data-atlas="clear">Limpar anotação</button><div class="eyebrow atlas-layer-title">NO PAPEL</div><button data-layer="relief" aria-pressed="true">Relevo</button><button data-layer="roads" aria-pressed="true">Estradas</button><button data-layer="places" aria-pressed="true">Lugares conhecidos</button><p class="atlas-note">O papel ganha marcas conforme você atravessa o mundo.</p></aside><div class="atlas-stage"><canvas id="map-canvas" aria-label="Mapa interativo do território: arraste para explorar e use a roda para aproximar" tabindex="0"></canvas><div class="atlas-zoom"><button data-atlas="in" aria-label="Aproximar mapa">+</button><button data-atlas="out" aria-label="Afastar mapa">−</button></div></div></div><footer class="atlas-footer"><span>Arraste o papel · Roda aproxima · Clique anota · M fecha</span><span id="atlas-coordinate"></span></footer></dialog>
<input type="file" id="import-file" accept="application/json,.json">`;
}
